name: roef-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi
  - uvicorn
  - scikit-learn=1.2.2
  - numpy
  - pandas
  - joblib
  - pydantic
  - pytest
  - requests
  - gunicorn  # Optional, for production deployments
